# Colors to use for plotting - from the Goodreads website
color_gr_brown: "#2A1404"
color_gr_purple: "#732151"
color_gr_green: "#E4F4DA"
color_gr_tan_background: "#F4F1EA"

coolors_dark_green: "#498467"
coolors_blue: "#376996"
coolors_dark_cyan: "#4B8F8C"
coolors_orange: "#F96900"
coolors_yellow: "#D19C1D"
